name: Build

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the operating system for the runner

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
